# See https://www.loraserver.io/lora-app-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://loraserver_as:loraserver_as@postgresql/loraserver_as?sslmode=disable"

[redis]
url="redis://redis:6379"

# BEGIN MQTT Client config
[application_server.integration.mqtt]
server="ssl://broker.save-lora.resourcepool.io:8883"
username="admin"
password="PndxCFsgXLW72tFwQ1yvZHyvTWcTOMMd"
# END MQTT Client config

[application_server.api]
public_host="appserver:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
# BEGIN SECRET
jwt_secret="7OqhtveFlyyZHTQvxuqtaEtbaywhqxoF5oFu6yQaHyA="
# END SECRET
