version: "3.7"
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'

services:
  db:
    image: mysql:8.0.14
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {{ save_lora_db_root_password }}
      MYSQL_USER: {{ save_lora_db_username }}
      MYSQL_PASSWORD: {{ save_lora_db_password }}
      MYSQL_DATABASE: {{ save_lora_db_database }}
    volumes:
      - /etc/appserver/conf/db/init:/docker-entrypoint-initdb.d
      - /opt/appserver/db:/var/lib/mysql
    logging: *default-logging
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    logging: *default-logging
  appserver:
    image: {{ save_lora_api_image }}
    ports:
      - 8080:3333
    volumes:
      - /etc/appserver/conf/config.ts:/server/src/config.ts:ro
    logging: *default-logging
  website:
    image: {{ save_lora_web_image }}
    ports:
      - 3000:80
    logging: *default-logging
