version: "3.7"

services:
  db:
    image: mysql:8.0.14
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # FIXME
      MYSQL_DATABASE: lora # FIXME
    volumes:
      - /etc/appserver/db/init:/docker-entrypoint-initdb.d
      - /opt/appserver/db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 3333:8080
  appserver:
    image: {{ save_lora_api_image }}
    ports:
      - 8080:3333
    volumes:
      - /etc/appserver/conf/config.ts:/server/src/config.ts:ro
  website:
    image: {{ save_lora_web_image }}
    ports:
      - 3000:80
