# See https://www.loraserver.io/lora-gateway-bridge/install/config/ for a full
# configuration example and documentation.

[backend.mqtt]
server="ssl://broker.save-lora.takima.io:8883"
username=""
password=""
