version: "3.7"

services:
  loraserver:
    image: loraserver/loraserver:2
    ports:
      - 8000:8000 # exposed port & API for lora-app-server or third-party-app-servers
    volumes:
      - /etc/loraserver/conf/loraserver:/etc/loraserver
  appserver:
    image: loraserver/lora-app-server:2
    ports:
      - 8080:8080 # public web-interface & public API port
      # - 8001:8001 not exposed: loraserver to lora-app-server private communication only
      - 8003:8003 # exposed port, join-server API
    volumes:
      - /etc/loraserver/conf/lora-app-server:/etc/lora-app-server
  geoserver:
    image: loraserver/lora-geo-server:2
    ports:
      - 8005:8005 # exposed port, geo-server API
    volumes:
      - /etc/loraserver/conf/lora-geo-server:/etc/lora-geo-server
  postgresql:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - /etc/loraserver/conf/postgresql/initdb:/docker-entrypoint-initdb.d
      - /opt/loraserver/db:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    volumes:
      - /opt/loraserver/redis:/data

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - /etc/loraserver/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /opt/loraserver/broker/data:/mosquitto/data
      - /opt/loraserver/broker/log:/mosquitto/log
      - /etc/letsencrypt/archive/loras.save-lora.takima.io:/etc/letsencrypt/archive/loras.save-lora.takima.io
      - /etc/letsencrypt/live/loras.save-lora.takima.io:/etc/letsencrypt/live/certs
    ports:
      - 8883:8883
