- hosts: loraserver
  roles:
    - role: nginx
      become: yes
    - role: certbot
      become: yes
    - role: loraserver
      become: yes
      ansible_user: "{{system_user}}"
      service_name: "loraserver"
  vars:
    nginx_proxy:
      - {name: loraserver-admin, host: admin.save-lora.takima.io, cert: loras.save-lora.takima.io, port: 8080}
    certbot_admin_email: contact@loicortola.com
    certbot_install_from_source: yes
    certbot_create_if_missing: yes
    certbot_package: certbot
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user }}"
    certbot_auto_renew_hour: 3
    certbot_auto_renew_minute: 30
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_certs:
      - domains:
        - loras.save-lora.takima.io
        - loraas.save-lora.takima.io
        - broker.save-lora.takima.io
        - admin.save-lora.takima.io
    certbot_create_standalone_stop_services:
      - nginx
