export const countries = [
    { value: 'AE', viewValue: 'United Arab Emirates'},
    { value: 'AF', viewValue: 'Afghanistan'},
    { value: 'AG', viewValue: 'Antigua & Barbuda'},
    { value: 'AI', viewValue: 'Anguilla'},
    { value: 'AL', viewValue: 'Albania'},
    { value: 'AM', viewValue: 'Armenia'},
    { value: 'AO', viewValue: 'Angola'},
    { value: 'AQ', viewValue: 'Antarctica'},
    { value: 'AR', viewValue: 'Argentina'},
    { value: 'AS', viewValue: 'American Samoa'},
    { value: 'AT', viewValue: 'Austria'},
    { value: 'AU', viewValue: 'Australia'},
    { value: 'AW', viewValue: 'Aruba'},
    { value: 'AX', viewValue: 'Åland Islands'},
    { value: 'AZ', viewValue: 'Azerbaijan'},
    { value: 'BA', viewValue: 'Bosnia & Herzegovina'},
    { value: 'BB', viewValue: 'Barbados'},
    { value: 'BD', viewValue: 'Bangladesh'},
    { value: 'BE', viewValue: 'Belgium'},
    { value: 'BF', viewValue: 'Burkina Faso'},
    { value: 'BG', viewValue: 'Bulgaria'},
    { value: 'BH', viewValue: 'Bahrain'},
    { value: 'BI', viewValue: 'Burundi'},
    { value: 'BJ', viewValue: 'Benin'},
    { value: 'BL', viewValue: 'St. Barthélemy'},
    { value: 'BM', viewValue: 'Bermuda'},
    { value: 'BN', viewValue: 'Brunei'},
    { value: 'BO', viewValue: 'Bolivia'},
    { value: 'BQ', viewValue: 'Caribbean Netherlands'},
    { value: 'BR', viewValue: 'Brazil'},
    { value: 'BS', viewValue: 'Bahamas'},
    { value: 'BT', viewValue: 'Bhutan'},
    { value: 'BW', viewValue: 'Botswana'},
    { value: 'BY', viewValue: 'Belarus'},
    { value: 'BZ', viewValue: 'Belize'},
    { value: 'CA', viewValue: 'Canada'},
    { value: 'CC', viewValue: 'Cocos (Keeling) Islands'},
    { value: 'CD', viewValue: 'Congo - Kinshasa'},
    { value: 'CF', viewValue: 'Central African Republic'},
    { value: 'CG', viewValue: 'Congo - Brazzaville'},
    { value: 'CH', viewValue: 'Switzerland'},
    { value: 'CI', viewValue: 'Côte d’Ivoire'},
    { value: 'CK', viewValue: 'Cook Islands'},
    { value: 'CL', viewValue: 'Chile'},
    { value: 'CM', viewValue: 'Cameroon'},
    { value: 'CN', viewValue: 'China'},
    { value: 'CO', viewValue: 'Colombia'},
    { value: 'CR', viewValue: 'Costa Rica'},
    { value: 'CU', viewValue: 'Cuba'},
    { value: 'CV', viewValue: 'Cape Verde'},
    { value: 'CW', viewValue: 'Curaçao'},
    { value: 'CX', viewValue: 'Christmas Island'},
    { value: 'CY', viewValue: 'Cyprus'},
    { value: 'CZ', viewValue: 'Czechia'},
    { value: 'DE', viewValue: 'Germany'},
    { value: 'DG', viewValue: 'Diego Garcia'},
    { value: 'DJ', viewValue: 'Djibouti'},
    { value: 'DK', viewValue: 'Denmark'},
    { value: 'DM', viewValue: 'Dominica'},
    { value: 'DO', viewValue: 'Dominican Republic'},
    { value: 'DZ', viewValue: 'Algeria'},
    { value: 'EA', viewValue: 'Ceuta & Melilla'},
    { value: 'EC', viewValue: 'Ecuador'},
    { value: 'EE', viewValue: 'Estonia'},
    { value: 'EG', viewValue: 'Egypt'},
    { value: 'EH', viewValue: 'Western Sahara'},
    { value: 'ER', viewValue: 'Eritrea'},
    { value: 'ES', viewValue: 'Spain'},
    { value: 'ET', viewValue: 'Ethiopia'},
    { value: 'EZ', viewValue: 'Eurozone'},
    { value: 'FI', viewValue: 'Finland'},
    { value: 'FJ', viewValue: 'Fiji'},
    { value: 'FK', viewValue: 'Falkland Islands'},
    { value: 'FM', viewValue: 'Micronesia'},
    { value: 'FO', viewValue: 'Faroe Islands'},
    { value: 'FR', viewValue: 'France'},
    { value: 'GA', viewValue: 'Gabon'},
    { value: 'GB', viewValue: 'United Kingdom'},
    { value: 'GD', viewValue: 'Grenada'},
    { value: 'GE', viewValue: 'Georgia'},
    { value: 'GF', viewValue: 'French Guiana'},
    { value: 'GG', viewValue: 'Guernsey'},
    { value: 'GH', viewValue: 'Ghana'},
    { value: 'GI', viewValue: 'Gibraltar'},
    { value: 'GL', viewValue: 'Greenland'},
    { value: 'GM', viewValue: 'Gambia'},
    { value: 'GN', viewValue: 'Guinea'},
    { value: 'GP', viewValue: 'Guadeloupe'},
    { value: 'GQ', viewValue: 'Equatorial Guinea'},
    { value: 'GR', viewValue: 'Greece'},
    { value: 'GS', viewValue: 'South Georgia & South Sandwich Islands'},
    { value: 'GT', viewValue: 'Guatemala'},
    { value: 'GU', viewValue: 'Guam'},
    { value: 'GW', viewValue: 'Guinea-Bissau'},
    { value: 'GY', viewValue: 'Guyana'},
    { value: 'HK', viewValue: 'Hong Kong SAR China'},
    { value: 'HN', viewValue: 'Honduras'},
    { value: 'HR', viewValue: 'Croatia'},
    { value: 'HT', viewValue: 'Haiti'},
    { value: 'HU', viewValue: 'Hungary'},
    { value: 'IC', viewValue: 'Canary Islands'},
    { value: 'ID', viewValue: 'Indonesia'},
    { value: 'IE', viewValue: 'Ireland'},
    { value: 'IL', viewValue: 'Israel'},
    { value: 'IM', viewValue: 'Isle of Man'},
    { value: 'IN', viewValue: 'India'},
    { value: 'IO', viewValue: 'British Indian Ocean Territory'},
    { value: 'IQ', viewValue: 'Iraq'},
    { value: 'IR', viewValue: 'Iran'},
    { value: 'IS', viewValue: 'Iceland'},
    { value: 'IT', viewValue: 'Italy'},
    { value: 'JE', viewValue: 'Jersey'},
    { value: 'JM', viewValue: 'Jamaica'},
    { value: 'JO', viewValue: 'Jordan'},
    { value: 'JP', viewValue: 'Japan'},
    { value: 'KE', viewValue: 'Kenya'},
    { value: 'KG', viewValue: 'Kyrgyzstan'},
    { value: 'KH', viewValue: 'Cambodia'},
    { value: 'KI', viewValue: 'Kiribati'},
    { value: 'KM', viewValue: 'Comoros'},
    { value: 'KN', viewValue: 'St. Kitts & Nevis'},
    { value: 'KP', viewValue: 'North Korea'},
    { value: 'KR', viewValue: 'South Korea'},
    { value: 'KW', viewValue: 'Kuwait'},
    { value: 'KY', viewValue: 'Cayman Islands'},
    { value: 'KZ', viewValue: 'Kazakhstan'},
    { value: 'LA', viewValue: 'Laos'},
    { value: 'LB', viewValue: 'Lebanon'},
    { value: 'LC', viewValue: 'St. Lucia'},
    { value: 'LI', viewValue: 'Liechtenstein'},
    { value: 'LK', viewValue: 'Sri Lanka'},
    { value: 'LR', viewValue: 'Liberia'},
    { value: 'LS', viewValue: 'Lesotho'},
    { value: 'LT', viewValue: 'Lithuania'},
    { value: 'LU', viewValue: 'Luxembourg'},
    { value: 'LV', viewValue: 'Latvia'},
    { value: 'LY', viewValue: 'Libya'},
    { value: 'MA', viewValue: 'Morocco'},
    { value: 'MC', viewValue: 'Monaco'},
    { value: 'MD', viewValue: 'Moldova'},
    { value: 'ME', viewValue: 'Montenegro'},
    { value: 'MF', viewValue: 'St. Martin'},
    { value: 'MG', viewValue: 'Madagascar'},
    { value: 'MH', viewValue: 'Marshall Islands'},
    { value: 'MK', viewValue: 'Macedonia'},
    { value: 'ML', viewValue: 'Mali'},
    { value: 'MM', viewValue: 'Myanmar (Burma)'},
    { value: 'MN', viewValue: 'Mongolia'},
    { value: 'MO', viewValue: 'Macau SAR China'},
    { value: 'MP', viewValue: 'Northern Mariana Islands'},
    { value: 'MQ', viewValue: 'Martinique'},
    { value: 'MR', viewValue: 'Mauritania'},
    { value: 'MS', viewValue: 'Montserrat'},
    { value: 'MT', viewValue: 'Malta'},
    { value: 'MU', viewValue: 'Mauritius'},
    { value: 'MV', viewValue: 'Maldives'},
    { value: 'MW', viewValue: 'Malawi'},
    { value: 'MX', viewValue: 'Mexico'},
    { value: 'MY', viewValue: 'Malaysia'},
    { value: 'MZ', viewValue: 'Mozambique'},
    { value: 'NA', viewValue: 'Namibia'},
    { value: 'NC', viewValue: 'New Caledonia'},
    { value: 'NE', viewValue: 'Niger'},
    { value: 'NF', viewValue: 'Norfolk Island'},
    { value: 'NG', viewValue: 'Nigeria'},
    { value: 'NI', viewValue: 'Nicaragua'},
    { value: 'NL', viewValue: 'Netherlands'},
    { value: 'NO', viewValue: 'Norway'},
    { value: 'NP', viewValue: 'Nepal'},
    { value: 'NR', viewValue: 'Nauru'},
    { value: 'NU', viewValue: 'Niue'},
    { value: 'NZ', viewValue: 'New Zealand'},
    { value: 'OM', viewValue: 'Oman'},
    { value: 'PA', viewValue: 'Panama'},
    { value: 'PE', viewValue: 'Peru'},
    { value: 'PF', viewValue: 'French Polynesia'},
    { value: 'PG', viewValue: 'Papua New Guinea'},
    { value: 'PH', viewValue: 'Philippines'},
    { value: 'PK', viewValue: 'Pakistan'},
    { value: 'PL', viewValue: 'Poland'},
    { value: 'PM', viewValue: 'St. Pierre & Miquelon'},
    { value: 'PN', viewValue: 'Pitcairn Islands'},
    { value: 'PR', viewValue: 'Puerto Rico'},
    { value: 'PS', viewValue: 'Palestinian Territories'},
    { value: 'PT', viewValue: 'Portugal'},
    { value: 'PW', viewValue: 'Palau'},
    { value: 'PY', viewValue: 'Paraguay'},
    { value: 'QA', viewValue: 'Qatar'},
    { value: 'RE', viewValue: 'Réunion'},
    { value: 'RO', viewValue: 'Romania'},
    { value: 'RS', viewValue: 'Serbia'},
    { value: 'RU', viewValue: 'Russia'},
    { value: 'RW', viewValue: 'Rwanda'},
    { value: 'SA', viewValue: 'Saudi Arabia'},
    { value: 'SB', viewValue: 'Solomon Islands'},
    { value: 'SC', viewValue: 'Seychelles'},
    { value: 'SD', viewValue: 'Sudan'},
    { value: 'SE', viewValue: 'Sweden'},
    { value: 'SG', viewValue: 'Singapore'},
    { value: 'SH', viewValue: 'St. Helena'},
    { value: 'SI', viewValue: 'Slovenia'},
    { value: 'SJ', viewValue: 'Svalbard & Jan Mayen'},
    { value: 'SK', viewValue: 'Slovakia'},
    { value: 'SL', viewValue: 'Sierra Leone'},
    { value: 'SM', viewValue: 'San Marino'},
    { value: 'SN', viewValue: 'Senegal'},
    { value: 'SO', viewValue: 'Somalia'},
    { value: 'SR', viewValue: 'Suriname'},
    { value: 'SS', viewValue: 'South Sudan'},
    { value: 'ST', viewValue: 'São Tomé & Príncipe'},
    { value: 'SV', viewValue: 'El Salvador'},
    { value: 'SX', viewValue: 'Sint Maarten'},
    { value: 'SY', viewValue: 'Syria'},
    { value: 'SZ', viewValue: 'Swaziland'},
    { value: 'TA', viewValue: 'Tristan da Cunha'},
    { value: 'TC', viewValue: 'Turks & Caicos Islands'},
    { value: 'TD', viewValue: 'Chad'},
    { value: 'TF', viewValue: 'French Southern Territories'},
    { value: 'TG', viewValue: 'Togo'},
    { value: 'TH', viewValue: 'Thailand'},
    { value: 'TJ', viewValue: 'Tajikistan'},
    { value: 'TK', viewValue: 'Tokelau'},
    { value: 'TL', viewValue: 'Timor-Leste'},
    { value: 'TM', viewValue: 'Turkmenistan'},
    { value: 'TN', viewValue: 'Tunisia'},
    { value: 'TO', viewValue: 'Tonga'},
    { value: 'TR', viewValue: 'Turkey'},
    { value: 'TT', viewValue: 'Trinidad & Tobago'},
    { value: 'TV', viewValue: 'Tuvalu'},
    { value: 'TW', viewValue: 'Taiwan'},
    { value: 'TZ', viewValue: 'Tanzania'},
    { value: 'UA', viewValue: 'Ukraine'},
    { value: 'UG', viewValue: 'Uganda'},
    { value: 'UM', viewValue: 'U.S. Outlying Islands'},
    { value: 'UN', viewValue: 'United Nations'},
    { value: 'US', viewValue: 'United States'},
    { value: 'UY', viewValue: 'Uruguay'},
    { value: 'UZ', viewValue: 'Uzbekistan'},
    { value: 'VA', viewValue: 'Vatican City'},
    { value: 'VC', viewValue: 'St. Vincent & Grenadines'},
    { value: 'VE', viewValue: 'Venezuela'},
    { value: 'VG', viewValue: 'British Virgin Islands'},
    { value: 'VI', viewValue: 'U.S. Virgin Islands'},
    { value: 'VN', viewValue: 'Vietnam'},
    { value: 'VU', viewValue: 'Vanuatu'},
    { value: 'WF', viewValue: 'Wallis & Futuna'},
    { value: 'WS', viewValue: 'Samoa'},
    { value: 'XK', viewValue: 'Kosovo'},
    { value: 'YE', viewValue: 'Yemen'},
    { value: 'YT', viewValue: 'Mayotte'},
    { value: 'ZA', viewValue: 'South Africa'},
    { value: 'ZM', viewValue: 'Zambia'},
    { value: 'ZW', viewValue: 'Zimbabwe'}
];
