---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: Install nginx
  yum: name=nginx state=present
  become: yes

- name: Remove nginx default
  file: path=/etc/nginx/conf.d/default.conf state=absent
  become: yes

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
  become: yes

- name: Copy nginx website configuration
  template: src=website-https.conf.j2 dest=/etc/nginx/conf.d/{{item.host}}.conf
  notify: restart nginx
  become: yes
  with_items: "{{ nginx_proxy }}"
  
- firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled
    
- firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled